### ISSUE TITLE
Межстрочное расстояние

### ISSUE THREAD

**Issue by PgLoLo** [SergeyGorchakov/russian-phd-thesis-template-typst#2]
С текущими настрйокамимежстрочное расстояние просто огромно. На 1.5 это не похоже. Выглядит как будто 
```typst
set par(leading: 1.5em)
``` 
делает не то, что нужно. Как в этом убедиться точно я не знаю, но вот, к примеру, сравнение с межстрочным расстоянием полтора для гугл дока, латеха и typst:
Google Doc:
![image](https://github.com/SergeyGorchakov/russian-phd-thesis-template-typst/assets/5480856/d2638d8d-a3a0-47ef-9690-5213ba66fb03)
Latex:
![image](https://github.com/SergeyGorchakov/russian-phd-thesis-template-typst/assets/5480856/a25e8dfa-ec07-453a-af79-fda7441e1315)
Typst:
![image](https://github.com/SergeyGorchakov/russian-phd-thesis-template-typst/assets/5480856/3a1fb413-8b2e-4d00-8f0c-853ceb856a1b)

У меня не получилось получить одинаковый результат даже для гуглдока с латехом, но в тайпсте межстрочные расстояния совсем гигантские. 

Нет ли тут какой-то ошибки? может параметр leading в функции par означает не совсем то с типографической точки зрения, что должен?

**Comment by SergeyGorchakov** [comment]
@PgLoLo какие предложения по исправлению этой ошибки?

**Comment by PgLoLo** [comment]
@SergeyGorchakov 

Согласно [этому](https://github.com/typst/typst/discussions/4397#discussioncomment-9781485) обсуждению, межстрочное расстояние обычно -- это расстояние между базовыми линиями соседних строк. А параемтр leading в typst -- это расстояние между верхней и нижней границами.

Как формально точно вычислить перерасчёт одного в другое -- что-то мне не особо понятно. Но как будто на глаз сделать параметр leading `1em` а не `1.5em` очень сильно похоже на правду. У себя в тексте я так и сделал, результатом удовлетворён.

**Comment by SergeyGorchakov** [comment]
@PgLoLo 
Сделайте PR :) 
Займусь выпуском версии 0.0.2

**Comment by SergeyGorchakov** [comment]
иисправлено
